### ISSUE TITLE
slow loading time

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#7]
The gem [nevir/Bumbler](https://github.com/nevir/Bumbler) reports a rather slow loading time of the pragmatic_tokenizer gem. I have not been able to find out why yet, and it's not a major issue, but probably something to keep track of.

Here are comparisons to other common gems my app requires:
````
1..10 ms: quiet_assets, byebug, stackprof, connection_pool, turbolinks, bootstrap-sass,…
10..30 ms: coffee-rails, simple_form, will_paginate, pg, rollbar, sidekiq,…
30..50 ms: dalli, jbuilder
50..100 ms: sidekiq, pragmatic_segmenter
100..300 ms: slim-rails, pragmatic_tokenizer, devise, twitter
300..500 ms: sass-rails, mechanize, rails
````
I just wonder what the reason for the comparably slow loading time of pragmatic_tokenizer is.

**Comment by diasks2** [comment]
I have a hunch that maybe the slow loading time is due to the fact that the `unicode` gem dependency is rather large (1.59MB). For this reason, and another (I needed a pure Ruby implementation of the unicode upcase and downcase functionality for a Shoes gem) I have tried making another [gem](https://rubygems.org/gems/unicode_case_converter) (`unicode_case_converter`) that mimics the upcase and downcase functionality of the unicode gem but is much smaller (17KB). 

But... I need your help if possible. When tested within that gem, it seems that the gem performs in line if not a little faster than the unicode gem: https://github.com/diasks2/unicode_case_converter/blob/master/spec/unicode_case_converter_spec.rb#L89-L114

However, if I try to swap out this gem for the unicode gem in pragmatic_tokenizer than pragmatic_tokenizer grinds to a halt. Any ideas as to why?

**Comment by maia** [comment]
I'm not sure. Could it be because of GC kicking in after a while, as you're chaining `.gsub`? You won't notice that until a while. Also I believe it would be a better solution to create a replacement hash and use this for gsub, and to use constants too, as every string you pass to gsub will be recreated (and not reused) too.
Btw, have you seen the [ActiveSupport implementation](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/multibyte/unicode.rb) of unicode downcasing? Wouldn't it be an option just to use this part of ActiveSupport instead of the Unicode gem?

**Comment by diasks2** [comment]
I'm going to close this one as I think your optimizations have fixed this. I checked in bumbler and it is down to 57.68ms.
